//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Inicio {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Inicio() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generad.Resources.Inicio.Inicio", typeof(Inicio).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Áreas de acción.
        /// </summary>
        public static string Areas_de_accion {
            get {
                return ResourceManager.GetString("Areas_de_accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comercialización.
        /// </summary>
        public static string Comercializacion {
            get {
                return ResourceManager.GetString("Comercializacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar y exportar cualquier producto que requiera el cliente.
        /// </summary>
        public static string Comercializacion_1 {
            get {
                return ResourceManager.GetString("Comercializacion_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofrecer  la mejor calidad y precio al mercado de salud, tecnológico, industrial y de alimentos.
        /// </summary>
        public static string Comercializacion_2 {
            get {
                return ResourceManager.GetString("Comercializacion_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cómo lo hacemos?.
        /// </summary>
        public static string Como_lo_hacemos {
            get {
                return ResourceManager.GetString("Como_lo_hacemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escuchandolo y comprendiendo sus necesidades.
        /// </summary>
        public static string Como_lo_hacemos_1 {
            get {
                return ResourceManager.GetString("Como_lo_hacemos_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reuniendo a las mejores empresas para realizar un análisis de todos los factores que intervienen en la realidad de forma vertical y, transversalmente.
        /// </summary>
        public static string Como_lo_hacemos_2 {
            get {
                return ResourceManager.GetString("Como_lo_hacemos_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encontrando las mejores opciones de solución y proponiendolas a los clientes.
        /// </summary>
        public static string Como_lo_hacemos_3 {
            get {
                return ResourceManager.GetString("Como_lo_hacemos_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordinando el conocimiento y experiencia de las mejores empresas y profesionistas de cada ramo para llevarlas a la realidad.
        /// </summary>
        public static string Como_lo_hacemos_4 {
            get {
                return ResourceManager.GetString("Como_lo_hacemos_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Implementando la solución y dando seguimiento a los resultados.
        /// </summary>
        public static string Como_lo_hacemos_5 {
            get {
                return ResourceManager.GetString("Como_lo_hacemos_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Holding.
        /// </summary>
        public static string Holding {
            get {
                return ResourceManager.GetString("Holding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollo de negocios nuevos.
        /// </summary>
        public static string Holding_1 {
            get {
                return ResourceManager.GetString("Holding_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optimizar el desarrollo de negocios en proceso de ejecución.
        /// </summary>
        public static string Holding_2 {
            get {
                return ResourceManager.GetString("Holding_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mediar en conflictos empresariales: técnicos, legales o de costos.
        /// </summary>
        public static string Holding_3 {
            get {
                return ResourceManager.GetString("Holding_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integración profesional.
        /// </summary>
        public static string Integracion_personal {
            get {
                return ResourceManager.GetString("Integracion_personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aumentar los conocimientos y habilidades de profesionistas, así como complementar su actitud acorde con las necesidades organizacionales.
        /// </summary>
        public static string Integracion_personal_1 {
            get {
                return ResourceManager.GetString("Integracion_personal_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo que hacemos.
        /// </summary>
        public static string Lo_que_hacemos {
            get {
                return ResourceManager.GetString("Lo_que_hacemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aumentar sus ganancias y las de su empresa.
        /// </summary>
        public static string Lo_que_hacemos_1 {
            get {
                return ResourceManager.GetString("Lo_que_hacemos_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantener competitiva su empresa.
        /// </summary>
        public static string Lo_que_hacemos_2 {
            get {
                return ResourceManager.GetString("Lo_que_hacemos_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resolver los problemas que tenga su empresa.
        /// </summary>
        public static string Lo_que_hacemos_3 {
            get {
                return ResourceManager.GetString("Lo_que_hacemos_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presentación.
        /// </summary>
        public static string Presentacion {
            get {
                return ResourceManager.GetString("Presentacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMENZAR.
        /// </summary>
        public static string Presentacion_conector {
            get {
                return ResourceManager.GetString("Presentacion_conector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LLEVE SU NEGOCIO A NUEVOS ÉXITOS.
        /// </summary>
        public static string Presentacion_eslogan {
            get {
                return ResourceManager.GetString("Presentacion_eslogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SABER MÁS.
        /// </summary>
        public static string Presentacion_llave {
            get {
                return ResourceManager.GetString("Presentacion_llave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollo, consultoría y asesoría.
        /// </summary>
        public static string Presentacion_subtitulo {
            get {
                return ResourceManager.GetString("Presentacion_subtitulo", resourceCulture);
            }
        }
    }
}
