//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Comercializacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Comercializacion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generad.Resources.Comercializacion.Comercializacion", typeof(Comercializacion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Commodities.
        /// </summary>
        public static string commodities {
            get {
                return ResourceManager.GetString("commodities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minerales y alimentos.
        /// </summary>
        public static string commodities_1 {
            get {
                return ResourceManager.GetString("commodities_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipo médico.
        /// </summary>
        public static string equipo_medico {
            get {
                return ResourceManager.GetString("equipo_medico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Somos asociados por proyecto con las marcas líderes de equipamiento médico para hospitales, clínicas y consultorios médicos.
        /// </summary>
        public static string equipo_medico_1 {
            get {
                return ResourceManager.GetString("equipo_medico_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuerza productora.
        /// </summary>
        public static string fuerza_productora {
            get {
                return ResourceManager.GetString("fuerza_productora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Representamos a: 
        ///
        ///más de 5,000 apicultores en todo México y 
        ///
        ///tenemos convenio con las 3 principales envasadoras que cumplen con los más estrictos requisitos para exportación, para poder surtir, desde frascos de 350 gramos hasta barriles de 300 kilogramos.
        /// </summary>
        public static string fuerza_productora_1 {
            get {
                return ResourceManager.GetString("fuerza_productora_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La miel en el mundo.
        /// </summary>
        public static string la_miel_en_el_mundo {
            get {
                return ResourceManager.GetString("la_miel_en_el_mundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La miel es un alimento, por lo que lo regulan organismos especializados en todo el mundo como: 
        ///La Administración de Comida y Drogas de los Estados Unidos o Food and Drug Administration, FDA,  
        ///El Códex Alimentarius que es una iniciativa de la Organización Mundial de la Salud, OMS y 
        ///La Autoridad Europea de Seguridad Alimentaria o European Food Safety Authority, EFSA. 
        ///
        ///En México la autoridad reguladora es SENASICA, perteneciente a la Organización Agropecuaria Oficial y que homologa sus principios y re [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string la_miel_en_el_mundo_1 {
            get {
                return ResourceManager.GetString("la_miel_en_el_mundo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las mieles más apreciadas son las de Brasil, España y México por su pureza, propiedades medicinales y propiedades alimenticias. 
        ///
        ///La Biblioteca Nacional de Medicina de Estados Unidos registra 320 tipos de miel; y en México se tienen más de 250 de ellas.
        /// </summary>
        public static string la_miel_en_el_mundo_2 {
            get {
                return ResourceManager.GetString("la_miel_en_el_mundo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a maquinaria.
        /// </summary>
        public static string maquinaria {
            get {
                return ResourceManager.GetString("maquinaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contamos con asociados con los mejores arrendadores de maquinaria para construcción.
        /// </summary>
        public static string maquinaria_1 {
            get {
                return ResourceManager.GetString("maquinaria_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miel.
        /// </summary>
        public static string miel {
            get {
                return ResourceManager.GetString("miel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miel mexicana multiflora.
        /// </summary>
        public static string miel_mexicana_multiflora {
            get {
                return ResourceManager.GetString("miel_mexicana_multiflora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es la más vendida en México, Estados Unidos de América, y Asia, ya que las abejas productoras MELÍFERAS, que viajan por muchas regiones del basto territorio mexicano. Produciendo miel de mezcla de sabores y consistencias. 
        ///
        ///Los apicultores mexicanos la homogenizan creando un estandar de sabor conocido en todo el mundo por un sabor dulce con un toque  ácido que la hace exquisita.
        /// </summary>
        public static string miel_mexicana_multiflora_1 {
            get {
                return ResourceManager.GetString("miel_mexicana_multiflora_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miel mexicana uniflora.
        /// </summary>
        public static string miel_mexicana_uniflora {
            get {
                return ResourceManager.GetString("miel_mexicana_uniflora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En México se tienen flores endémicas que producen un polen que, al ser procesadas por la abeja, crean una miel dulce, semi ácida y semi amarga.
        /// </summary>
        public static string miel_mexicana_uniflora_1 {
            get {
                return ResourceManager.GetString("miel_mexicana_uniflora_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mieles endémicas mexicanas son la de Mezquite, Tojonal, Aguacate, Dzizilche, Jabín.
        /// </summary>
        public static string miel_mexicana_uniflora_2 {
            get {
                return ResourceManager.GetString("miel_mexicana_uniflora_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ventaja de la Miel Mexicana, sobre los demás países, es que se cosecha durante todo el año por el clima tan bondadoso que tiene. 
        ///
        ///Un ejemplo es la miel de NARANJA su miel son &quot;pequeñas gotas color ámbar claro&quot;  es la miel dulce de los demás cítricos. 
        ///
        ///Su sabor es delicado y muy floral, es un tipo de miel que casi no cristaliza. 
        ///
        ///Su sabor combina perfecto con infusiones y postres con fruta..
        /// </summary>
        public static string miel_mexicana_uniflora_3 {
            get {
                return ResourceManager.GetString("miel_mexicana_uniflora_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso de venta (paso 1).
        /// </summary>
        public static string proceso_de_venta_paso1 {
            get {
                return ResourceManager.GetString("proceso_de_venta_paso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elegir.
        /// </summary>
        public static string proceso_de_venta_paso1_1 {
            get {
                return ResourceManager.GetString("proceso_de_venta_paso1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso de venta (paso 2).
        /// </summary>
        public static string proceso_de_venta_paso2 {
            get {
                return ResourceManager.GetString("proceso_de_venta_paso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llamar al nuestra oficina en México al +52 5547392178 de Lunes a Viernes de 10 hrs a 17 hrs para información de envío y tiempo de enrtega y realizar el pedido.
        /// </summary>
        public static string proceso_de_venta_paso2_1 {
            get {
                return ResourceManager.GetString("proceso_de_venta_paso2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso de venta (paso 3).
        /// </summary>
        public static string proceso_de_venta_paso3 {
            get {
                return ResourceManager.GetString("proceso_de_venta_paso3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificado el importe, la cantidad y el tipo de envasado, se le enviará la factura y la forma de pago.
        /// </summary>
        public static string proceso_de_venta_paso3_1 {
            get {
                return ResourceManager.GetString("proceso_de_venta_paso3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso de venta (paso4).
        /// </summary>
        public static string proceso_de_venta_paso4 {
            get {
                return ResourceManager.GetString("proceso_de_venta_paso4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestra empresa transportadora y/o exportadora la entregará en donde lo necesite.
        /// </summary>
        public static string proceso_de_venta_paso4_1 {
            get {
                return ResourceManager.GetString("proceso_de_venta_paso4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos sustentables.
        /// </summary>
        public static string productos_sustentables {
            get {
                return ResourceManager.GetString("productos_sustentables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creemos en la sustentabilidad como una parte obligatoria de la producción industrial, por ello comercializamos cualquier producto con certificados de protección y de beneficio a la naruraleza.
        /// </summary>
        public static string productos_sustentables_1 {
            get {
                return ResourceManager.GetString("productos_sustentables_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos y servicios.
        /// </summary>
        public static string productos_y_servicios {
            get {
                return ResourceManager.GetString("productos_y_servicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver catálogo.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
