//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Documental_form {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Documental_form() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generad.Resources.Documental_form.Documental_form", typeof(Documental_form).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evidencia.
        /// </summary>
        public static string documetal_forms {
            get {
                return ResourceManager.GetString("documetal_forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Currícula.
        /// </summary>
        public static string documetal_forms_1 {
            get {
                return ResourceManager.GetString("documetal_forms_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevos proyectos.
        /// </summary>
        public static string documetal_forms_2 {
            get {
                return ResourceManager.GetString("documetal_forms_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona.
        /// </summary>
        public static string opcion {
            get {
                return ResourceManager.GetString("opcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Genera D S.A. de C.V..
        /// </summary>
        public static string opcion_1 {
            get {
                return ResourceManager.GetString("opcion_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ING. Jorge Suárez Pineda.
        /// </summary>
        public static string opcion_2 {
            get {
                return ResourceManager.GetString("opcion_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plantas de incineración de residuos.
        /// </summary>
        public static string opcion_3 {
            get {
                return ResourceManager.GetString("opcion_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad médica sustentable.
        /// </summary>
        public static string opcion_4 {
            get {
                return ResourceManager.GetString("opcion_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollo de negocios sustentables.
        /// </summary>
        public static string opcion_5 {
            get {
                return ResourceManager.GetString("opcion_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hospitales alta especialidad sustentables.
        /// </summary>
        public static string opcion_6 {
            get {
                return ResourceManager.GetString("opcion_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de documento es requerido.
        /// </summary>
        public static string tipo_error {
            get {
                return ResourceManager.GetString("tipo_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento es requerido.
        /// </summary>
        public static string tipo_error_2 {
            get {
                return ResourceManager.GetString("tipo_error_2", resourceCulture);
            }
        }
    }
}
