//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Holding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Holding() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generad.Resources.Holding.Holding", typeof(Holding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes de gobiernos.
        /// </summary>
        public static string clientes_de_gobiernos {
            get {
                return ResourceManager.GetString("clientes_de_gobiernos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Federal, estatal o municipal.
        /// </summary>
        public static string clientes_de_gobiernos_1 {
            get {
                return ResourceManager.GetString("clientes_de_gobiernos_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ofrecemos desarrollo de proyectos de infraestructura partiendo de las necesidades que requiera la población en las áreas de: 
        ///
        ///SALUD (hospitales generales y de alta especialidad; de plantas de tratamiento, reciclamiento e incineración de Residuos Sólidos con generación de energía WTE y plantas de tratamiento de agua residual y plantas potabilizadoras), 
        ///
        ///VIALIDADES TERRESTRES Y ACUÁTICAS (públicas o concesionadas), y 
        ///
        ///CIUDADES SUSTENTABLES, SIN INVERSIÓN GUBERNAMENTAL.
        /// </summary>
        public static string clientes_de_gobiernos_2 {
            get {
                return ResourceManager.GetString("clientes_de_gobiernos_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofrecemos contactar a los gobiernos con las mejores y mas honestas empresas de diseño, diseño arquitectónico, construcción, equipamiento de infraestrucura, operación y manteniminto de inmuebles.
        /// </summary>
        public static string clientes_de_gobiernos_3 {
            get {
                return ResourceManager.GetString("clientes_de_gobiernos_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofrecemos financiamiento de infraestructura pública para ASOCIACIONES PÚBLICO-PRIVADAS.
        /// </summary>
        public static string clientes_de_gobiernos_4 {
            get {
                return ResourceManager.GetString("clientes_de_gobiernos_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofrecemos transversalmente mediación de conflictos técnicos, legales y/o económicos con empresas contratadas como contratistas o proveedores, profesionistas u otros gobiernos federales o gobiernos de estados o departamentos y/o gobiernos municipales.
        /// </summary>
        public static string clientes_de_gobiernos_5 {
            get {
                return ResourceManager.GetString("clientes_de_gobiernos_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes privados.
        /// </summary>
        public static string clientes_privados {
            get {
                return ResourceManager.GetString("clientes_privados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes profesionales.
        /// </summary>
        public static string clientes_profesionales {
            get {
                return ResourceManager.GetString("clientes_profesionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Independientes.
        /// </summary>
        public static string clientes_profesionales_1 {
            get {
                return ResourceManager.GetString("clientes_profesionales_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofrecemos desarrollar su potencial y sumarlos a los proyectos conservando su individualidad.
        /// </summary>
        public static string clientes_profesionales_2 {
            get {
                return ResourceManager.GetString("clientes_profesionales_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresas grandes.
        /// </summary>
        public static string empresas_grandes {
            get {
                return ResourceManager.GetString("empresas_grandes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofrecemos optimización y auditoría a su modelo de negocio mediante asesoría y consultoría técnica y legal para conflictos empresariales, anteriores o actuales, además de ofrecer propuesta de proyectos con financiamiento y su realización garantizada mediante factoraje.
        /// </summary>
        public static string empresas_grandes_1 {
            get {
                return ResourceManager.GetString("empresas_grandes_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofrecemos financiamiento, tecnología y supervisión legal para ASOCIACIONES PÚBLICO-PRIVADAS, CONCESIONES y ASIGNACIONES POR ESPECIALIDAD.
        /// </summary>
        public static string empresas_grandes_2 {
            get {
                return ResourceManager.GetString("empresas_grandes_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofrecemos transversalmente mediación de conflictos técnicos, legales y/o económicos con otras empresas o con gobiernos federales, gobiernos de estados o departamentos y/o gobiernos municipales, con garantía de cobranza.
        /// </summary>
        public static string empresas_grandes_3 {
            get {
                return ResourceManager.GetString("empresas_grandes_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresas medianas.
        /// </summary>
        public static string empresas_medianas {
            get {
                return ResourceManager.GetString("empresas_medianas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofrecemos optimización de su modelo de negocio mediante auditorías técnicas, legales y financieras, propuesta de proyectos con financiamiento y su realización garantizada.
        /// </summary>
        public static string empresas_medianas_1 {
            get {
                return ResourceManager.GetString("empresas_medianas_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofrecemos mediación de conflictos técnicos, legales y/o económicos con otras empresas o con gobiernos federales, gobiernos de estados o departamentos y/o gobiernos municipales. 
        ///
        ///Utilizamos soluciones transversales que beneficien a todas las partes.
        /// </summary>
        public static string empresas_medianas_2 {
            get {
                return ResourceManager.GetString("empresas_medianas_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresas micro.
        /// </summary>
        public static string empresas_micro {
            get {
                return ResourceManager.GetString("empresas_micro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofrecemos modelos de negocios de rápida recuperación de inversión con utilidad proporcional.
        /// </summary>
        public static string empresas_micro_1 {
            get {
                return ResourceManager.GetString("empresas_micro_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresas pequeñas.
        /// </summary>
        public static string empresas_pequeñas {
            get {
                return ResourceManager.GetString("empresas_pequeñas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofrecemos modelos de negocios de alta recuperación de inversión, cartera de clientes y capital revolvente de fondos de inversión.
        /// </summary>
        public static string empresas_pequeñas_1 {
            get {
                return ResourceManager.GetString("empresas_pequeñas_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Independientes.
        /// </summary>
        public static string independientes {
            get {
                return ResourceManager.GetString("independientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofrecemos desarrollar su potencial y sumarlos a los proyectos conservando su individualidad.
        /// </summary>
        public static string independientes_1 {
            get {
                return ResourceManager.GetString("independientes_1", resourceCulture);
            }
        }
    }
}
