//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generad.Resources.Nosotros.Union {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Union {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Union() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generad.Resources.Nosotros.Union.Union", typeof(Union).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formación del holding.
        /// </summary>
        internal static string formacion_del_holding {
            get {
                return ResourceManager.GetString("formacion_del_holding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con los excelentes resultados obtenidos hasta ese momento, todos los participantes decidimos formar un &quot;frente empresarial&quot;, es decir, que cada empresa y profesionista participante ofrezcan &quot;lo mejor que tengan&quot; para beneficiar al mismo cliente. Esto se traduce en que, sin importar el tamaño del proyecto, problema o situación, el cliente, SIEMPRE TENDRÁ LA PARTICIPACIÓN DE LOS MEJORES PROFESIONISTAS cobrando un importe menor al comercial.  
        ///
        ///Por lo anterior, en 2015 fusionamos las tres empresas fundadoras [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string formacion_del_holding_1 {
            get {
                return ResourceManager.GetString("formacion_del_holding_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unión de fuerzas.
        /// </summary>
        internal static string union_de_fuerzas {
            get {
                return ResourceManager.GetString("union_de_fuerzas", resourceCulture);
            }
        }
    }
}
