//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generad.Resources.Nosotros.Renacer {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Renacer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Renacer() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generad.Resources.Nosotros.Renacer.Renacer", typeof(Renacer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelos de negocios.
        /// </summary>
        internal static string modelos__de__negocios {
            get {
                return ResourceManager.GetString("modelos _de _negocios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renacer al siglo XXI.
        /// </summary>
        internal static string renacer_al__siglo_XXI {
            get {
                return ResourceManager.GetString("renacer_al _siglo_XXI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En el incipiente siglo XXI, probamos con &quot;modelos de negocio&quot; exitosos de todo el mundo, y los adecuamos a las condiciones locales del País o Región en donde realizamos los proyectos, teniendo un gran éxito económico y laboral gracias a que utilizamos a la transversalidad legal-técnica-económica como elemento indispensable para cumplir los objetivos de cada proyecto.
        /// </summary>
        internal static string renacer_al_siglo_XXI {
            get {
                return ResourceManager.GetString("renacer_al_siglo_XXI", resourceCulture);
            }
        }
    }
}
