//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generad.Resources.Nosotros.Existimos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Existimos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Existimos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generad.Resources.Nosotros.Existimos.Existimos", typeof(Existimos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alcance.
        /// </summary>
        internal static string alcance {
            get {
                return ResourceManager.GetString("alcance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestras empresas asociadas y sus profesionistas garantizan cumplir los objetivos elegidos por el cliente.
        /// </summary>
        internal static string alcance_1 {
            get {
                return ResourceManager.GetString("alcance_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utilizando nuestra red de herramientas jurídicas, técnicas y legales.
        /// </summary>
        internal static string alcance_2 {
            get {
                return ResourceManager.GetString("alcance_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizando nuestros conocimientos permanentemente y analizando los más recientes éxitos de otros casos similares.
        /// </summary>
        internal static string alcance_3 {
            get {
                return ResourceManager.GetString("alcance_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Misión.
        /// </summary>
        internal static string mision {
            get {
                return ResourceManager.GetString("mision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su éxito.
        /// </summary>
        internal static string misión_1 {
            get {
                return ResourceManager.GetString("misión_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para que existimos.
        /// </summary>
        internal static string para_que_existimos {
            get {
                return ResourceManager.GetString("para_que_existimos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Política empresarial.
        /// </summary>
        internal static string politica_empresarial {
            get {
                return ResourceManager.GetString("politica_empresarial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nos comprometemos con nuestros clientes en obtener el éxito que eligen.
        /// </summary>
        internal static string politica_empresarial_1 {
            get {
                return ResourceManager.GetString("politica_empresarial_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visión.
        /// </summary>
        internal static string vision {
            get {
                return ResourceManager.GetString("vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ser la mejor empresa que ofrezca soluciones específicas y transversales.
        /// </summary>
        internal static string vision_1 {
            get {
                return ResourceManager.GetString("vision_1", resourceCulture);
            }
        }
    }
}
