//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class integracion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal integracion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generad.Resources.Integracion.integracion", typeof(integracion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunicación efectiva.
        /// </summary>
        public static string comunicacion_efectiva {
            get {
                return ResourceManager.GetString("comunicacion_efectiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estandarizamos los entendimientos entre pares y colaboradores, para llegar a acuerdos y cumplirlos.
        /// </summary>
        public static string comunicacion_efectiva_1 {
            get {
                return ResourceManager.GetString("comunicacion_efectiva_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollo de negocios y desarrollo humano: conocimientos.
        /// </summary>
        public static string desarrollo_de_negocios {
            get {
                return ResourceManager.GetString("desarrollo_de_negocios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollo de negocios y desarrollo humano: actitudes.
        /// </summary>
        public static string desarrollo_de_negocios_actitudes {
            get {
                return ResourceManager.GetString("desarrollo_de_negocios_actitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollo de negocios y desarrollo humano: habilidades.
        /// </summary>
        public static string desarrollo_de_negocios_habilidades {
            get {
                return ResourceManager.GetString("desarrollo_de_negocios_habilidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disciplina institucional, responsabilidad y disposición.
        /// </summary>
        public static string disciplina_institucional_responsabilidad {
            get {
                return ResourceManager.GetString("disciplina_institucional_responsabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estandarizamos los criterios individuales en colectivos de la organización de conformidad con su misión y políticas empresariales y de calidad.
        /// </summary>
        public static string disciplina_institucional_responsabilidad_1 {
            get {
                return ResourceManager.GetString("disciplina_institucional_responsabilidad_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizamos talleres lúdicos y vivenciales en lugares armónicos.
        /// </summary>
        public static string disciplina_institucional_responsabilidad_2 {
            get {
                return ResourceManager.GetString("disciplina_institucional_responsabilidad_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrenamiento y formación de empleados empresariales y de gobierno.
        /// </summary>
        public static string entrenamiento_y_formacion {
            get {
                return ResourceManager.GetString("entrenamiento_y_formacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizamos evaluaciones objetivas, estandarizamos las habilidades requeridas y potenciamos las de especialidad.
        /// </summary>
        public static string entrenamiento_y_formacion_1 {
            get {
                return ResourceManager.GetString("entrenamiento_y_formacion_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elaboramos e impartimos talleres lúdicos, enfocados a sus objetivos a alcanzar.
        /// </summary>
        public static string entrenamiento_y_formacion_2 {
            get {
                return ResourceManager.GetString("entrenamiento_y_formacion_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formación directiva.
        /// </summary>
        public static string formacion_directiva {
            get {
                return ResourceManager.GetString("formacion_directiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generales y especializados para empresas y gobiernos.
        /// </summary>
        public static string generales_y_especializados {
            get {
                return ResourceManager.GetString("generales_y_especializados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizamos evaluaciones objetivas, estandarizamos los conocimientos requeridos y potenciamos los de especialidad.
        /// </summary>
        public static string generales_y_especializados_1 {
            get {
                return ResourceManager.GetString("generales_y_especializados_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elaboramos y/o impartimos cursos, seminarios, pláticas o conferencias, desde 1 persona en adelante.
        /// </summary>
        public static string generales_y_especializados_2 {
            get {
                return ResourceManager.GetString("generales_y_especializados_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visión de negocio.
        /// </summary>
        public static string vision_de_negocio {
            get {
                return ResourceManager.GetString("vision_de_negocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nos especializamos en enseñar metodologías exitosas para que los directivos establezcan rutas sencillas y claras para alcanzar el objetivo de su área acorde con la misión y política organizacional.
        /// </summary>
        public static string vision_de_negocio_1 {
            get {
                return ResourceManager.GetString("vision_de_negocio_1", resourceCulture);
            }
        }
    }
}
