//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class paraqueexistimos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal paraqueexistimos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generad.Resources.Nosotros.para_que_existimos.paraqueexistimos", typeof(paraqueexistimos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Misión.
        /// </summary>
        public static string paraqueexistimos_1 {
            get {
                return ResourceManager.GetString("paraqueexistimos_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizando nuestros conocimientos permanentemente y analizando los más recientes éxitos de otros casos similares.
        /// </summary>
        public static string paraqueexistimos_10 {
            get {
                return ResourceManager.GetString("paraqueexistimos_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su éxito.
        /// </summary>
        public static string paraqueexistimos_2 {
            get {
                return ResourceManager.GetString("paraqueexistimos_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visión.
        /// </summary>
        public static string paraqueexistimos_3 {
            get {
                return ResourceManager.GetString("paraqueexistimos_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ser la mejor empresa que ofrezca soluciones específicas y transversales.
        /// </summary>
        public static string paraqueexistimos_4 {
            get {
                return ResourceManager.GetString("paraqueexistimos_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Política empresarial.
        /// </summary>
        public static string paraqueexistimos_5 {
            get {
                return ResourceManager.GetString("paraqueexistimos_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nos comprometemos con nuestros clientes en obtener el éxito que eligen.
        /// </summary>
        public static string paraqueexistimos_6 {
            get {
                return ResourceManager.GetString("paraqueexistimos_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alcance.
        /// </summary>
        public static string paraqueexistimos_7 {
            get {
                return ResourceManager.GetString("paraqueexistimos_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utilizando nuestra red de herramientas jurídicas, técnicas y legales..
        /// </summary>
        public static string paraqueexistimos_8 {
            get {
                return ResourceManager.GetString("paraqueexistimos_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestras empresas asociadas y sus profesionistas garantizan cumplir los objetivos elegidos por el cliente..
        /// </summary>
        public static string paraqueexistimos_9 {
            get {
                return ResourceManager.GetString("paraqueexistimos_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para que existimos.
        /// </summary>
        public static string paraqueexistimos_t {
            get {
                return ResourceManager.GetString("paraqueexistimos_t", resourceCulture);
            }
        }
    }
}
