//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Contacto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contacto() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generad.Resources.Contacto.Contacto", typeof(Contacto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string Boton_form {
            get {
                return ResourceManager.GetString("Boton_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GeneraD.
        /// </summary>
        public static string CorreoContacto {
            get {
                return ResourceManager.GetString("CorreoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gracias por contactarnos.
        /// </summary>
        public static string CorreoContacto_1 {
            get {
                return ResourceManager.GetString("CorreoContacto_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gracias por contactarnos, pronto nos estaremos contactando con usted..
        /// </summary>
        public static string CorreoContacto_2 {
            get {
                return ResourceManager.GetString("CorreoContacto_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string Email_form {
            get {
                return ResourceManager.GetString("Email_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email es requirido.
        /// </summary>
        public static string Email_form_error {
            get {
                return ResourceManager.GetString("Email_form_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Correo no es una dirección de correo electrónico válida..
        /// </summary>
        public static string Email_no_es {
            get {
                return ResourceManager.GetString("Email_no_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario.
        /// </summary>
        public static string Mensaje_form {
            get {
                return ResourceManager.GetString("Mensaje_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario es requerido.
        /// </summary>
        public static string Mensaje_form_error {
            get {
                return ResourceManager.GetString("Mensaje_form_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        public static string Nombre_form {
            get {
                return ResourceManager.GetString("Nombre_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo es requerido.
        /// </summary>
        public static string Nombre_form_error {
            get {
                return ResourceManager.GetString("Nombre_form_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la empresa.
        /// </summary>
        public static string NombreCompania_form {
            get {
                return ResourceManager.GetString("NombreCompania_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre compañia es requerido.
        /// </summary>
        public static string NombreCompania_form_error {
            get {
                return ResourceManager.GetString("NombreCompania_form_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string Telefono_form {
            get {
                return ResourceManager.GetString("Telefono_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono es requerido.
        /// </summary>
        public static string Telefono_form_error {
            get {
                return ResourceManager.GetString("Telefono_form_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Teléfono debe ser un número..
        /// </summary>
        public static string Telefono_no_es {
            get {
                return ResourceManager.GetString("Telefono_no_es", resourceCulture);
            }
        }
    }
}
