//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generad.Resources.Nosotros.QuienesSomos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class quienes_somos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal quienes_somos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generad.Resources.Nosotros.QuienesSomos.quienes_somos", typeof(quienes_somos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quienes somos.
        /// </summary>
        public static string Quienes__somos {
            get {
                return ResourceManager.GetString("Quienes _somos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivo empresarial.
        /// </summary>
        public static string Quienes_somos_1 {
            get {
                return ResourceManager.GetString("Quienes_somos_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a somos una empresa holding con 54 años de experiencia, undiendo a 23 empresas, en las áreas: 
        ///*legales (de proyectos individuales, de la empresa, comercial y asuntos penales), 
        ///*financieros, 
        ///*organizacionales, 
        ///*ecológicos (sustentabilidad ambiental y económica), 
        ///*de creación de infraestructura humana (constructoras , supervisoras y auditoras),
        ///*de desarrollo de negocio, 
        ///*de desarrollo y aplicación de tecnologías, 
        ///*de comercio (importación y exportación), 
        ///* de desarrollo humano (empresas capaci [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Quienes_somos_2 {
            get {
                return ResourceManager.GetString("Quienes_somos_2", resourceCulture);
            }
        }
    }
}
